title: MinBatis
description: A desired IntelliJ IDEA plugin working with MyBatis framework.
google_analytics: UA-72182328-2
show_downloads: true
theme: jekyll-theme-cayman
pname: MinBatis
pid: 13720-minbatis